# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 901da3a08ed03814bdfee4a357520f3291186be07ad2438a11dfef7dae964b29e539de06c44bce4f1f32bf98e893ff031a9d3ae4bc44c9e525e19fc0ff590b72

test:
  secret_key_base: a806f0c9c3ddecfbab3113a06d652fd7fa27377140970956249d9bae6603195114f057a3ed4b7a4d7b471c7347b913341d99f63a2df16868094ee7651e640cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
